name: CounterStrike
version: '1.0-SNAPSHOT'
main: io.github.miaow233.counterstrike.CounterStrike
api-version: '1.20'
commands:
  setlobby:
    description: 'Set lobby'
    usage: /setlobby
    permission: counterstrike.setlobby
  setteamspawn:
    description: 'Set team spawn'
    usage: '/setteamspawn <team>'
    permission: counterstrike.setteamspawn
  join:
    description: 'Join the game'
    usage: /join