name: CounterStrike
version: '1.0-SNAPSHOT'
main: io.github.miaow233.counterstrike.CounterStrike
api-version: '1.20'
load: POSTWORLD
commands:
  'csmc coin':
    permission: csmc.admin
  'csmc map':
    permission: csmc.admin
  'csmc join':
    permission: csmc.join
  'csmc end':
    permission: csmc.leave
  'csmc':
    usage: '/csmc'
    aliases:
      - 'cs'
    permission: csmc
