name: CounterStrike
version: '1.0-SNAPSHOT'
main: io.github.miaow233.counterstrike.CounterStrike
api-version: '1.20'
load: POSTWORLD
commands:
  'csmc admin':
    description: 'Open the admin menu'
    aliases:
      - 'csmc admin'
    permission: csmc.admin

  'csmc':
    usage: '/csmc'
    description: 'Open the main menu'
    aliases:
      - 'cs'
    permission: csmc
